// <auto-generated />
namespace HistoricBlog.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodanie_config_repo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodanie_config_repo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181250565_dodanie_config_repo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
